"""Dark-theme figures for the learned-representations study, from committed artifacts.

Reads:
    artifacts/multitask_metrics.json + learning_curves.npz  (Pillar 1)
    artifacts/ensemble_uncertainty.json                     (Pillar 2)
    artifacts/attention_attribution.json                    (interpretability probe)
    artifacts/pretrain_ablation.json                        (Pillar 1 ablation)

Writes (SNPTX git-dark theme, matching feasibility_and_figures.py):
    figures/fig_transfer_curves.png       data-efficiency curves (transfer evidence)
    figures/fig_ensemble_calibration.png  ECE/NLL/Brier horizontal comparisons
    figures/fig_conformal_efficiency.png  nominal-target set size, realized coverage, selection
    figures/fig_attention_probe.png       constant-score diagnostic and GAT predictive AUROC
    figures/fig_pretrain_ablation.png     SSL pretraining delta over from-scratch
    figures/fig_campaign_efficiency.png   retrospective stopping counts and comparator caps

Every figure is regenerated by this script; captions in the manuscript/notebook name it.
Run after the GPU artifacts exist:
    PYTHONPATH=src:. python preprint/dl_forward/figures.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = next(p for p in HERE.parents if (p / "src").is_dir())  # repo root (public or private layout)
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.colors import to_rgba  # noqa: E402

from snptx.viz.theme import (  # noqa: E402
    BORDER,
    CARD_BG,
    DARK_BG,
    NEON_BLUE,
    NEON_GREY,
    NEON_GREEN,
    NEON_YELLOW,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
)

from mtl_config import ENDPOINTS  # noqa: E402

ART = HERE / "artifacts"
FIGDIR = HERE / "figures"
FIGDIR.mkdir(exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 150, "savefig.dpi": 200, "font.size": 11, "font.family": "DejaVu Sans",
    "figure.facecolor": DARK_BG, "savefig.facecolor": DARK_BG,
    "axes.facecolor": CARD_BG, "axes.edgecolor": BORDER,
    "axes.labelcolor": TEXT_SECONDARY, "axes.titlecolor": TEXT_PRIMARY,
    "text.color": TEXT_PRIMARY, "xtick.color": TEXT_SECONDARY, "ytick.color": TEXT_SECONDARY,
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.color": BORDER, "grid.alpha": 0.4, "axes.axisbelow": True,
    "legend.facecolor": CARD_BG, "legend.edgecolor": BORDER, "legend.framealpha": 0.9,
})

# Method colors, consistent across figures. House style: neon blue / yellow / green,
# with a bright grey reserved for the reference/baseline series (no orange).
#   RF descriptor baseline -> grey     single-task GNN -> yellow
#   multi-task GNN         -> blue     MC-dropout      -> green
#   deep ensemble          -> blue (bold; only co-occurs with rf/single/mc, not multi)
C_RF, C_SINGLE, C_MULTI = NEON_GREY, NEON_YELLOW, NEON_BLUE
C_ENS, C_MC = NEON_BLUE, NEON_GREEN

# Thin, bright line/bar defaults so series stay legible on the dark canvas.
LW = 1.1
BAR_FILL_ALPHA = 0.22
BAR_EDGE_LW = 1.2


def _horizontal_comparison(ax, keys, res, metric, methods, baseline=0.0):
    """Show endpoint values with offset horizontal lines and distinct method markers."""
    y = np.arange(len(keys))
    for j, (method, color, label, marker) in enumerate(methods):
        values = [res[k][method][metric] for k in keys]
        positions = y + (j - (len(methods) - 1) / 2) * 0.18
        ax.hlines(positions, baseline, values, colors=color, linewidth=1.5)
        ax.plot(values, positions, marker, color=color, markersize=4, label=label)
    ax.set_yticks(y)
    ax.set_yticklabels([_PRETTY[k].split(" (")[0] for k in keys], fontsize=8.5)
    ax.invert_yaxis()
    ax.set_xlim(left=baseline)


def _uncertainty_methods():
    return (("rf", C_RF, "RF", "s"), ("gnn_single", C_SINGLE, "single GIN", "o"),
            ("mc_dropout", C_MC, "MC dropout", "^"),
            ("ensemble", C_ENS, "ensemble", "D"))

_PRETTY = {e.key: e.pretty for e in ENDPOINTS}


def _require(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"missing artifact {path}; regenerate its source results first")


# ---------------------------------------------------------------------------
# Pillar 1: data-efficiency (transfer) curves.
# ---------------------------------------------------------------------------
def fig_transfer_curves() -> None:
    _require(ART / "multitask_metrics.json")
    _require(ART / "learning_curves.npz")
    meta = json.loads((ART / "multitask_metrics.json").read_text())
    z = np.load(ART / "learning_curves.npz")
    fracs = z["_fractions"]
    keys = [e.key for e in ENDPOINTS]

    n = len(keys)
    ncol = 3
    nrow = int(np.ceil(n / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(4.2 * ncol, 3.4 * nrow))
    axes = np.atleast_1d(axes).ravel()

    for ax, k in zip(axes, keys):
        task = meta["summary"][k]["task"]
        metric = "auroc" if task == "clf" else "mae"
        higher_better = task == "clf"
        for method, color, label in ((("rf", C_RF, "RF"),
                                      ("gnn_single", C_SINGLE, "single-task GIN"),
                                      ("gnn_multi", C_MULTI, "multi-task GIN"))):
            arr = z[f"{k}__{method}__{metric}"]  # (n_frac, n_seed)
            mean = np.nanmean(arr, axis=1)
            sd = np.nanstd(arr, axis=1, ddof=1)  # sample s.d. over seeds
            ax.plot(fracs, mean, "-o", color=color, label=label, lw=LW, ms=4)
            ax.fill_between(fracs, mean - sd, mean + sd, color=color, alpha=0.12)
        ax.set_title(f"{_PRETTY[k]}", fontsize=10.5)
        ax.set_xlabel("retained training-scaffold fraction", fontsize=9)
        ylabel = "AUROC" if higher_better else (
            "MAE (logS)" if k == "solubility"
            else "MAE (TDC target scale)")
        ax.set_ylabel(ylabel, fontsize=9)
        ax.set_xticks(fracs)
    for ax in axes[n:]:
        ax.axis("off")
    axes[0].legend(loc="best", fontsize=8)
    fig.suptitle("Multitask and single-task performance across endpoints",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(FIGDIR / "fig_transfer_curves.png")
    plt.close(fig)
    print("wrote fig_transfer_curves.png")


# ---------------------------------------------------------------------------
# Pillar 2: ensemble calibration + conformal efficiency.
# ---------------------------------------------------------------------------
def _clf_endpoints(res: dict) -> list[str]:
    return [e.key for e in ENDPOINTS if e.task == "clf" and e.key in res]


def fig_ensemble_calibration() -> None:
    _require(ART / "ensemble_uncertainty.json")
    meta = json.loads((ART / "ensemble_uncertainty.json").read_text())
    res = meta["results"]
    keys = _clf_endpoints(res)
    methods = _uncertainty_methods()
    panels = (("ece", "ECE (lower better)"), ("nll", "NLL (lower better)"),
              ("brier", "Brier (lower better)"))

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.4))
    for ax, (metric, title) in zip(axes, panels):
        _horizontal_comparison(ax, keys, res, metric, methods)
        ax.set_title(title, fontsize=10.5)
        ax.set_xlabel(metric.upper())
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4, fontsize=8.5)
    fig.suptitle("Probability scoring and calibration on the fixed scaffold split",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0.08, 1, 0.95))
    fig.savefig(FIGDIR / "fig_ensemble_calibration.png")
    plt.close(fig)
    print("wrote fig_ensemble_calibration.png")


def fig_conformal_efficiency() -> None:
    _require(ART / "ensemble_uncertainty.json")
    meta = json.loads((ART / "ensemble_uncertainty.json").read_text())
    res = meta["results"]
    keys = _clf_endpoints(res)
    methods = _uncertainty_methods()

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(13, 4.4))
    _horizontal_comparison(ax1, keys, res, "conf_set_size_at_90", methods)
    ax1.axvline(1.0, color=TEXT_SECONDARY, ls="--", lw=1)
    ax1.set_xlabel("mean set size")
    ax1.set_title("Set size at nominal 90% target", fontsize=10.5)
    _horizontal_comparison(ax2, keys, res, "conf_coverage_at_90", methods, baseline=0.75)
    ax2.axvline(0.90, color=TEXT_SECONDARY, ls="--", lw=1)
    ax2.set_xlim(0.75, 1.0)
    ax2.set_xlabel("realized test coverage")
    ax2.set_title("Empirical coverage; dashed = 0.90", fontsize=10.5)
    _horizontal_comparison(ax3, keys, res, "sel_acc_at_70", methods)
    ax3.set_xlim(0, 1)
    ax3.set_xlabel("selective accuracy")
    ax3.set_title("Accuracy on most confident 70%", fontsize=10.5)
    handles, labels = ax1.get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=4, fontsize=8.5)
    fig.suptitle("Prediction-set size, empirical coverage, and selective accuracy",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    # Keep the first endpoint labels inside the canvas despite the wide panel titles.
    fig.subplots_adjust(left=0.055, right=0.99, bottom=0.22, top=0.78, wspace=0.27)
    fig.savefig(FIGDIR / "fig_conformal_efficiency.png")
    plt.close(fig)
    print("wrote fig_conformal_efficiency.png")


def fig_attention_probe() -> None:
    """Diagnose the constant incoming-attention sum; retain predictive AUROC separately."""
    _require(ART / "attention_attribution.json")
    _require(ART / "attention_nodes.npz")
    res = json.loads((ART / "attention_attribution.json").read_text())["results"]
    nodes = np.load(ART / "attention_nodes.npz")
    keys = list(res.keys())
    y = np.arange(len(keys))

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.5, 4.8))
    bins = np.linspace(-16, 16, 49)
    for k, color in zip(keys, (NEON_YELLOW, NEON_BLUE)):
        scores = nodes[f"{k}__scores"]
        label = f"{_PRETTY[k].split(' (')[0]}: s.d. {scores.std():.2e} (n = {len(scores):,})"
        ax1.hist((scores - 1.0) * 1e8, bins=bins, density=True, histtype="step",
                 color=color, linewidth=1.3, label=label)
    ax1.axvline(0.0, color=TEXT_SECONDARY, ls="--", lw=1)
    ax1.set_xlabel(r"stored incoming sum $-\,1$ ($\times 10^{-8}$)")
    ax1.set_ylabel("density")
    ax1.set_title("Normalized incoming sum = 1", fontsize=10.5)
    ax1.legend(loc="upper left", fontsize=7.5)
    predaucs = [res[k]["test_auroc"] for k in keys]
    ax2.hlines(y, 0, predaucs, color=NEON_BLUE, linewidth=1.5)
    ax2.scatter(predaucs, y, color=NEON_BLUE, s=50, zorder=3)
    for yi, value in zip(y, predaucs):
        ax2.text(value + 0.025, yi, f"{value:.3f}", color=NEON_BLUE,
                 fontsize=9, va="center")
    ax2.axvline(0.5, color=TEXT_SECONDARY, ls="--", lw=1)
    ax2.set_xlim(0, 1)
    ax2.set_ylim(len(keys) - 0.4, -0.4)
    ax2.set_yticks(y)
    ax2.set_yticklabels([_PRETTY[k].split(" (")[0] for k in keys])
    ax2.set_xlabel("test AUROC (dashed = chance)")
    ax2.set_title("GAT prediction; one unseeded run", fontsize=10.5)
    fig.suptitle("Attention-score implementation diagnostic",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.text(0.5, 0.025, "Atom-score differences are numerical residuals and cannot support a salience ranking.",
             ha="center", color=TEXT_SECONDARY, fontsize=9)
    fig.tight_layout(rect=(0, 0.08, 1, 0.95))
    fig.savefig(FIGDIR / "fig_attention_probe.png")
    plt.close(fig)
    print("wrote fig_attention_probe.png")


def fig_pretrain_ablation() -> None:
    """Pretraining ablation: does self-supervised attribute-mask pretraining help?

    Bars show the beneficial-direction delta (pretrained - scratch) in each endpoint's
    primary metric at the lowest training fraction, for single- and multi-task trunks.
    For MAE endpoints the sign is flipped so that up = improvement for every endpoint.
    """
    _require(ART / "pretrain_ablation.json")
    d = json.loads((ART / "pretrain_ablation.json").read_text())
    summ = d["summary"]
    keys = [e.key for e in ENDPOINTS]
    frac = min(d["config"]["train_fractions"])

    # Per-seed paired deltas from the raw records, so the error bar is the sample s.d.
    per_seed: dict[tuple[str, str], np.ndarray] = {}
    for k in keys:
        metric = summ[k]["metric"]
        for arm in ("single", "multi"):
            runs = {(r["method"], r["seed"]): r[metric] for r in d["records"]
                    if r["endpoint"] == k and abs(r["fraction"] - frac) < 1e-9}
            seeds = sorted(s for (m, s) in runs if m == f"{arm}_scratch")
            per_seed[(k, arm)] = np.array(
                [runs[(f"{arm}_pretrained", s)] - runs[(f"{arm}_scratch", s)] for s in seeds])

    def _delta(k, arm):
        sign = -1.0 if summ[k]["metric"] == "mae" else 1.0  # up = improvement
        deltas = per_seed[(k, arm)]
        return sign * float(deltas.mean()), float(deltas.std(ddof=1))

    w = 0.38
    fig, axes = plt.subplots(1, 3, figsize=(13, 4.8), gridspec_kw={"width_ratios": [2, 1, 1]})
    panels = [([k for k in keys if summ[k]["metric"] == "auroc"], "Classification", "ΔAUROC"),
              (["solubility"], "Solubility", "−ΔMAE (logS)"),
              (["caco2"], "Caco2", "−ΔMAE (TDC target scale)")]
    for ax, (panel_keys, title, ylabel) in zip(axes, panels):
        x = np.arange(len(panel_keys))
        for off, arm, col, lab in ((-w / 2, "single", C_SINGLE, "single-task"),
                                   (w / 2, "multi", C_MULTI, "multi-task")):
            vals = [_delta(k, arm)[0] for k in panel_keys]
            errs = [_delta(k, arm)[1] for k in panel_keys]
            ax.bar(x + off, vals, w, yerr=errs, capsize=3,
                   color=to_rgba(col, BAR_FILL_ALPHA), edgecolor=col, linewidth=BAR_EDGE_LW,
                   ecolor=col, error_kw={"elinewidth": 1.0}, label=lab)
        ax.axhline(0.0, color=TEXT_SECONDARY, ls="--", lw=1)
        ax.set_xticks(x)
        ax.set_xticklabels([_PRETTY[k].split(" (")[0] for k in panel_keys])
        ax.set_ylabel(ylabel, fontsize=10)
        ax.set_title(title, fontsize=10.5)
        ax.set_xlim(-0.6, len(panel_keys) - 0.4)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2, fontsize=9)
    fig.suptitle(f"Attribute-mask pretraining at retained scaffold fraction {frac:.2f}\n"
                 "Paired beneficial-direction changes; mean ± sample s.d. over five seeds",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0.08, 1, 0.98))
    fig.savefig(FIGDIR / "fig_pretrain_ablation.png")
    plt.close(fig)
    print("wrote fig_pretrain_ablation.png")


def fig_campaign_efficiency() -> None:
    """Retrospective stopping counts beside analytical requirements and subgroup caps."""
    from scipy.stats import norm

    _require(ART / "campaign_learned.json")
    d = json.loads((ART / "campaign_learned.json").read_text())
    per = d["per_endpoint"]
    keys = list(per.keys())
    y = np.arange(len(keys))
    used = [per[k]["sprt"]["n_measurements"] for k in keys]
    fixed = [per[k]["sprt"]["fixed_sample_n"] for k in keys]
    cfg = d["sprt"]
    n_analytic = ((norm.ppf(1 - cfg["alpha"]) + norm.ppf(1 - cfg["beta"]))
                  / cfg["meaningful_effect_sigma"]) ** 2
    feasible = np.array(fixed) >= n_analytic - 0.05
    used_feasible = sum(u for u, ok in zip(used, feasible) if ok)
    analytic_feasible = n_analytic * int(feasible.sum())
    pct = 100 * (1 - used_feasible / analytic_feasible)

    fig, ax = plt.subplots(figsize=(11, 4.8))
    for yi, u, f, ok in zip(y, used, fixed, feasible):
        ax.plot([f, u], [yi, yi], color=BORDER, lw=2)
        if u == f:
            ax.text(u + 2, yi, f"{u} used / capped", color=TEXT_PRIMARY,
                    va="center", fontsize=8.5)
        else:
            ax.text(f + 1, yi - 0.14, f"{f:.1f}" + (" cap" if not ok else ""),
                    color=NEON_GREY, va="bottom", fontsize=8.5)
            ax.text(u + 1, yi + 0.14, str(u), color=NEON_BLUE, va="top", fontsize=8.5)
        if ok:
            difference = f - u
            note = (f"{difference:.1f} fewer" if difference >= 0
                    else f"{-difference:.1f} more")
        else:
            note = "cap; lower nominal power" if u != f else "subgroup exhausted; undecided"
        ax.text(96, yi, note, color=TEXT_SECONDARY, va="center", fontsize=8.5)
    ax.scatter(np.array(fixed)[feasible], y[feasible], color=NEON_GREY, marker="s",
               s=65, zorder=3, label="analytical fixed-sample requirement")
    ax.scatter(np.array(fixed)[~feasible], y[~feasible], facecolors="none", edgecolors=NEON_GREY,
               marker="s", s=75, linewidths=1.5, zorder=3, label="available subgroup cap")
    ax.scatter(used, y, color=NEON_BLUE, s=65, zorder=4, label="SPRT measurements used")
    ax.set_xlim(0, 142)
    ax.set_ylim(len(keys) - 0.4, -0.4)
    ax.set_yticks(y)
    verdicts = {"reject_h0": "GO", "accept_h0": "NO-GO", "continue": "EXHAUSTED"}
    ax.set_yticklabels([
        f"{_PRETTY[k].split(' (')[0]} · {verdicts[per[k]['sprt']['decision']]}"
        for k in keys])
    for tick, k in zip(ax.get_yticklabels(), keys):
        tick.set_color(NEON_YELLOW if per[k]["sprt"]["decision"] == "continue" else NEON_GREEN)
    ax.set_xlabel("measurements used / analytical benchmark")
    ax.set_title(f"BBB + AMES: {used_feasible} used vs {analytic_feasible:.1f} analytical requirement "
                 f"({pct:.1f}% fewer)\nhERG and HIA comparators are capped below nominal power",
                 fontsize=10.5)
    handles, labels = ax.get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3, fontsize=8)
    fig.suptitle("Retrospective stopping on the ensemble-ranked subgroups",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0.09, 1, 0.92))
    fig.savefig(FIGDIR / "fig_campaign_efficiency.png")
    plt.close(fig)
    print("wrote fig_campaign_efficiency.png")


def main() -> None:
    made = []
    if (ART / "multitask_metrics.json").exists():
        fig_transfer_curves()
        made.append("transfer")
    if (ART / "ensemble_uncertainty.json").exists():
        fig_ensemble_calibration()
        fig_conformal_efficiency()
        made.append("ensemble")
    if (ART / "attention_attribution.json").exists():
        fig_attention_probe()
        made.append("attention")
    if (ART / "pretrain_ablation.json").exists():
        fig_pretrain_ablation()
        made.append("pretrain")
    if (ART / "campaign_learned.json").exists():
        fig_campaign_efficiency()
        made.append("campaign")
    if not made:
        raise SystemExit("no artifacts yet; run the GPU stage first")
    print("done:", made)


if __name__ == "__main__":
    main()
