"""Dark-theme figures for the DL-forward study (AGENT_09), from committed artifacts.

Reads:
    artifacts/multitask_metrics.json + learning_curves.npz  (Pillar 1)
    artifacts/ensemble_uncertainty.json                     (Pillar 2)
    artifacts/attention_attribution.json                    (interpretability probe)
    artifacts/pretrain_ablation.json                        (Pillar 1 ablation)

Writes (SNPTX git-dark theme, matching feasibility_and_figures.py):
    figures/fig_transfer_curves.png       data-efficiency curves (transfer evidence)
    figures/fig_ensemble_calibration.png  ECE/NLL/Brier bars, ensemble vs baselines
    figures/fig_conformal_efficiency.png  conformal set size at 90% coverage
    figures/fig_attention_probe.png       attention vs descriptor atom salience
    figures/fig_pretrain_ablation.png     SSL pretraining delta over from-scratch

Every figure is regenerated by this script; captions in the manuscript/notebook name it.
Run after the GPU artifacts exist:
    PYTHONPATH=src:. python pilot_phd/preprint/dl_forward/figures.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(ROOT))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.colors import to_rgba  # noqa: E402

from snptx.viz.theme import (  # noqa: E402
    BORDER,
    CARD_BG,
    DARK_BG,
    NEON_BLUE,
    NEON_GREY,
    NEON_PINK,
    NEON_YELLOW,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
)

from mtl_config import ENDPOINTS  # noqa: E402

ART = HERE / "artifacts"
FIGDIR = HERE / "figures"
FIGDIR.mkdir(exist_ok=True)

plt.rcParams.update({
    "figure.dpi": 150, "savefig.dpi": 200, "font.size": 11, "font.family": "DejaVu Sans",
    "figure.facecolor": DARK_BG, "savefig.facecolor": DARK_BG,
    "axes.facecolor": CARD_BG, "axes.edgecolor": BORDER,
    "axes.labelcolor": TEXT_SECONDARY, "axes.titlecolor": TEXT_PRIMARY,
    "text.color": TEXT_PRIMARY, "xtick.color": TEXT_SECONDARY, "ytick.color": TEXT_SECONDARY,
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.grid": True, "grid.color": BORDER, "grid.alpha": 0.4, "axes.axisbelow": True,
    "legend.facecolor": CARD_BG, "legend.edgecolor": BORDER, "legend.framealpha": 0.9,
})

# Method colors, consistent across figures. House style: neon blue / yellow / pink,
# with a bright grey reserved for the reference/baseline series (no orange).
#   RF descriptor baseline -> grey     single-task GNN -> yellow
#   multi-task GNN         -> blue     MC-dropout      -> pink
#   deep ensemble          -> blue (bold; only co-occurs with rf/single/mc, not multi)
C_RF, C_SINGLE, C_MULTI = NEON_GREY, NEON_YELLOW, NEON_BLUE
C_ENS, C_MC = NEON_BLUE, NEON_PINK

# Thin, bright line/bar defaults so series stay legible on the dark canvas.
LW = 1.1
BAR_FILL_ALPHA = 0.22
BAR_EDGE_LW = 1.2


def _neon_bar(ax, x, height, w, color, label=None):
    """Thin neon bar: translucent fill under a bright, crisp edge of the same hue."""
    return ax.bar(x, height, w, color=to_rgba(color, BAR_FILL_ALPHA),
                  edgecolor=color, linewidth=BAR_EDGE_LW, label=label)

_PRETTY = {e.key: e.pretty for e in ENDPOINTS}


def _require(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"missing artifact {path}; run the GPU stage first "
                         f"(make train-gnn / make_ensemble_uncertainty.py)")


# ---------------------------------------------------------------------------
# Pillar 1: data-efficiency (transfer) curves.
# ---------------------------------------------------------------------------
def fig_transfer_curves() -> None:
    _require(ART / "multitask_metrics.json")
    _require(ART / "learning_curves.npz")
    meta = json.loads((ART / "multitask_metrics.json").read_text())
    z = np.load(ART / "learning_curves.npz")
    fracs = z["_fractions"]
    keys = [e.key for e in ENDPOINTS]

    n = len(keys)
    ncol = 3
    nrow = int(np.ceil(n / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(4.2 * ncol, 3.4 * nrow))
    axes = np.atleast_1d(axes).ravel()

    for ax, k in zip(axes, keys):
        task = meta["summary"][k]["task"]
        metric = "auroc" if task == "clf" else "mae"
        higher_better = task == "clf"
        for method, color, label in ((("rf", C_RF, "RF"),
                                      ("gnn_single", C_SINGLE, "GNN-single"),
                                      ("gnn_multi", C_MULTI, "GNN-multi"))):
            arr = z[f"{k}__{method}__{metric}"]  # (n_frac, n_seed)
            mean = np.nanmean(arr, axis=1)
            sd = np.nanstd(arr, axis=1)
            ax.plot(fracs, mean, "-o", color=color, label=label, lw=LW, ms=4)
            ax.fill_between(fracs, mean - sd, mean + sd, color=color, alpha=0.12)
        ax.set_title(f"{_PRETTY[k]}", fontsize=10.5)
        ax.set_xlabel("training fraction")
        ax.set_ylabel(metric.upper() + (" (lower better)" if not higher_better else ""))
        ax.set_xticks(fracs)
    for ax in axes[n:]:
        ax.axis("off")
    axes[0].legend(loc="best", fontsize=8.5)
    fig.suptitle("Multi-task representation transfer: data-efficiency curves",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    fig.savefig(FIGDIR / "fig_transfer_curves.png")
    plt.close(fig)
    print("wrote fig_transfer_curves.png")


# ---------------------------------------------------------------------------
# Pillar 2: ensemble calibration + conformal efficiency.
# ---------------------------------------------------------------------------
def _clf_endpoints(res: dict) -> list[str]:
    return [e.key for e in ENDPOINTS if e.task == "clf" and e.key in res]


def fig_ensemble_calibration() -> None:
    _require(ART / "ensemble_uncertainty.json")
    meta = json.loads((ART / "ensemble_uncertainty.json").read_text())
    res = meta["results"]
    keys = _clf_endpoints(res)
    methods = (("rf", C_RF, "RF"), ("gnn_single", C_SINGLE, "single"),
               ("mc_dropout", C_MC, "MC-drop"), ("ensemble", C_ENS, "ensemble"))
    panels = (("ece", "ECE (lower better)"), ("nll", "NLL (lower better)"),
              ("brier", "Brier (lower better)"))

    fig, axes = plt.subplots(1, 3, figsize=(13, 4))
    x = np.arange(len(keys))
    w = 0.2
    for ax, (metric, title) in zip(axes, panels):
        for j, (m, color, label) in enumerate(methods):
            vals = [res[k][m][metric] for k in keys]
            _neon_bar(ax, x + (j - 1.5) * w, vals, w, color, label=label)
        ax.set_xticks(x)
        ax.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys], rotation=20, fontsize=8.5)
        ax.set_title(title, fontsize=10.5)
    axes[0].legend(loc="best", fontsize=8.5)
    fig.suptitle("Deep-ensemble calibration vs baselines",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(FIGDIR / "fig_ensemble_calibration.png")
    plt.close(fig)
    print("wrote fig_ensemble_calibration.png")


def fig_conformal_efficiency() -> None:
    _require(ART / "ensemble_uncertainty.json")
    meta = json.loads((ART / "ensemble_uncertainty.json").read_text())
    res = meta["results"]
    keys = _clf_endpoints(res)
    methods = (("rf", C_RF, "RF"), ("gnn_single", C_SINGLE, "single"),
               ("mc_dropout", C_MC, "MC-drop"), ("ensemble", C_ENS, "ensemble"))

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
    x = np.arange(len(keys))
    w = 0.2
    # left: mean conformal set size at 90% coverage (efficiency; lower is sharper).
    for j, (m, color, label) in enumerate(methods):
        vals = [res[k][m]["conf_set_size_at_90"] for k in keys]
        _neon_bar(ax1, x + (j - 1.5) * w, vals, w, color, label=label)
    ax1.axhline(1.0, color=BORDER, ls="--", lw=1)
    ax1.set_xticks(x)
    ax1.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys], rotation=20, fontsize=8.5)
    ax1.set_title("Conformal set size @ 90% coverage (lower = sharper)", fontsize=10.5)
    ax1.legend(loc="best", fontsize=8.5)
    # right: selective accuracy at 70% coverage (higher is better).
    for j, (m, color, label) in enumerate(methods):
        vals = [res[k][m]["sel_acc_at_70"] for k in keys]
        _neon_bar(ax2, x + (j - 1.5) * w, vals, w, color, label=label)
    ax2.set_xticks(x)
    ax2.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys], rotation=20, fontsize=8.5)
    ax2.set_title("Selective accuracy @ 70% coverage (higher better)", fontsize=10.5)
    fig.suptitle("Uncertainty to decisions: conformal efficiency and selective accuracy",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(FIGDIR / "fig_conformal_efficiency.png")
    plt.close(fig)
    print("wrote fig_conformal_efficiency.png")


def fig_attention_probe() -> None:
    """Interpretability probe: does attention recover the descriptor rule?"""
    _require(ART / "attention_attribution.json")
    res = json.loads((ART / "attention_attribution.json").read_text())["results"]
    keys = list(res.keys())
    x = np.arange(len(keys))
    w = 0.38

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10.5, 4.2))
    aucs = [res[k]["node_attention_auroc"] for k in keys]
    predaucs = [res[k]["test_auroc"] for k in keys]
    ax1.bar(x - w / 2, aucs, w, color=to_rgba(NEON_YELLOW, BAR_FILL_ALPHA),
            edgecolor=NEON_YELLOW, linewidth=BAR_EDGE_LW, label="attention → salience AUROC")
    ax1.bar(x + w / 2, predaucs, w, color=to_rgba(NEON_BLUE, BAR_FILL_ALPHA),
            edgecolor=NEON_BLUE, linewidth=BAR_EDGE_LW, label="GAT predictive AUROC")
    ax1.axhline(0.5, color=BORDER, ls="--", lw=1.2)
    ax1.text(len(keys) - 0.5, 0.52, "chance", color=TEXT_SECONDARY, fontsize=8.5, ha="right")
    ax1.set_xticks(x)
    ax1.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys])
    ax1.set_ylim(0, 1.0)
    ax1.set_title("Attention does not recover the descriptor rule", fontsize=10.5)
    ax1.legend(loc="lower right", fontsize=8.5)
    enr = [res[k]["topk_enrichment"] for k in keys]
    # pink = positive enrichment, grey = non-positive (near-zero / negative).
    colors = [NEON_PINK if v > 0 else NEON_GREY for v in enr]
    ax2.bar(x, enr, 0.5, color=[to_rgba(c, BAR_FILL_ALPHA) for c in colors],
            edgecolor=colors, linewidth=BAR_EDGE_LW)
    ax2.axhline(0.0, color=BORDER, ls="--", lw=1.2)
    ax2.set_xticks(x)
    ax2.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys])
    ax2.set_title("Top-3 attended-atom salient enrichment (near 0)", fontsize=10.5)
    fig.suptitle("Interpretability probe: attention vs descriptor atom salience",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(FIGDIR / "fig_attention_probe.png")
    plt.close(fig)
    print("wrote fig_attention_probe.png")


def fig_pretrain_ablation() -> None:
    """Pillar-1 ablation: does self-supervised node-mask pretraining help?

    Bars show the beneficial-direction delta (pretrained - scratch) in each endpoint's
    primary metric at the lowest training fraction, for single- and multi-task trunks.
    For MAE endpoints the sign is flipped so that up = improvement for every endpoint.
    """
    _require(ART / "pretrain_ablation.json")
    d = json.loads((ART / "pretrain_ablation.json").read_text())
    summ = d["summary"]
    keys = [e.key for e in ENDPOINTS]
    frac = min(d["config"]["train_fractions"])

    def _delta(k, arm):
        row = next(r for r in summ[k][arm] if abs(r["fraction"] - frac) < 1e-9)
        sign = -1.0 if summ[k]["metric"] == "mae" else 1.0  # up = improvement
        return sign * row["delta_mean"], row["delta_std"]

    x = np.arange(len(keys))
    w = 0.38
    fig, ax = plt.subplots(figsize=(10.5, 4.6))
    for off, arm, col, lab in ((-w / 2, "single", C_SINGLE, "single-task"),
                               (w / 2, "multi", C_MULTI, "multi-task")):
        vals = [_delta(k, arm)[0] for k in keys]
        errs = [_delta(k, arm)[1] for k in keys]
        ax.bar(x + off, vals, w, yerr=errs, capsize=3,
               color=to_rgba(col, BAR_FILL_ALPHA), edgecolor=col, linewidth=BAR_EDGE_LW,
               ecolor=col, error_kw={"elinewidth": 1.0}, label=f"{lab} + pretrain")
    ax.axhline(0.0, color=BORDER, ls="--", lw=1.2)
    ax.set_xticks(x)
    ax.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys])
    ax.set_ylabel(f"improvement from pretraining\n(beneficial direction, fraction {frac})")
    ax.set_title("Self-supervised node-mask pretraining (Hu et al. 2020): "
                 "delta over from-scratch", fontsize=11)
    ax.text(-0.45, 0.006, "no effect", color=TEXT_SECONDARY,
            fontsize=8.5, ha="left", va="bottom")
    ax.legend(loc="upper right", fontsize=9)
    fig.suptitle("Pillar-1 ablation: pretraining vs scratch at low data",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(FIGDIR / "fig_pretrain_ablation.png")
    plt.close(fig)
    print("wrote fig_pretrain_ablation.png")


def fig_campaign_efficiency() -> None:
    """Learned-oracle campaign: measurements used vs the fixed-sample budget, per endpoint.

    Sequential SPRT with the deep-ensemble oracle should reach a decision in fewer
    measurements than a fixed-sample design where the oracle's top-ranked subgroup is
    enriched. We plot both bars per endpoint and annotate the aggregate saving; the harder
    cases (BBB spends more, HIA undecided) are shown, not hidden.
    """
    _require(ART / "campaign_learned.json")
    d = json.loads((ART / "campaign_learned.json").read_text())
    per = d["per_endpoint"]
    s = d["summary"]
    keys = list(per.keys())
    x = np.arange(len(keys))
    w = 0.36
    used = [per[k]["sprt"]["n_measurements"] for k in keys]
    fixed = [per[k]["sprt"]["fixed_sample_n"] for k in keys]

    fig, ax = plt.subplots(figsize=(9.5, 4.6))
    # fixed-sample budget = grey reference; sequential (used) = bright blue.
    _neon_bar(ax, x - w / 2, fixed, w, NEON_GREY, label="fixed-sample budget")
    _neon_bar(ax, x + w / 2, used, w, NEON_BLUE, label="SPRT (sequential) used")
    for xi, (u, f) in enumerate(zip(used, fixed)):
        verdict = per[keys[xi]]["sprt"]["verdict"].split(" (")[0]
        ax.text(xi, max(u, f) + 2, verdict, ha="center", va="bottom",
                fontsize=8.0, color=TEXT_SECONDARY)
    ax.set_xticks(x)
    ax.set_xticklabels([_PRETTY[k].split(" (")[0] for k in keys])
    ax.set_ylabel("measurements to a decision")
    ax.set_title(f"Learned-oracle campaign: {s['total_measurements_used']} vs "
                 f"{s['total_fixed_sample']:.0f} measurements "
                 f"({s['pct_saved']}% saved, {s['n_go_decisions']}/{s['n_endpoints']} GO)",
                 fontsize=11)
    ax.legend(loc="upper right", fontsize=9)
    fig.suptitle("Sequential decision efficiency with the deep-ensemble oracle",
                 fontsize=13, fontweight="bold", color=TEXT_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.95))
    fig.savefig(FIGDIR / "fig_campaign_efficiency.png")
    plt.close(fig)
    print("wrote fig_campaign_efficiency.png")


def main() -> None:
    made = []
    if (ART / "multitask_metrics.json").exists():
        fig_transfer_curves()
        made.append("transfer")
    if (ART / "ensemble_uncertainty.json").exists():
        fig_ensemble_calibration()
        fig_conformal_efficiency()
        made.append("ensemble")
    if (ART / "attention_attribution.json").exists():
        fig_attention_probe()
        made.append("attention")
    if (ART / "pretrain_ablation.json").exists():
        fig_pretrain_ablation()
        made.append("pretrain")
    if (ART / "campaign_learned.json").exists():
        fig_campaign_efficiency()
        made.append("campaign")
    if not made:
        raise SystemExit("no artifacts yet; run the GPU stage first")
    print("done:", made)


if __name__ == "__main__":
    main()
