"""Generate the self-contained, figure-embedded submission Markdown from the
canonical dl_forward manuscript.

The canonical manuscript
(`MANUSCRIPT_learned_representations_admet.md`) stays the single source of
truth for prose and numbers. This script derives an upload-ready copy that
embeds each figure inline (numbered, captioned, with the regenerating script
named) so the artifact renders as a stand-alone document without pandoc or
LaTeX. Re-run after any manuscript edit:

    cd /home/snptx/snptx-core && source .venv/bin/activate
    python pilot_phd/preprint/dl_forward/make_submission.py
"""
from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "MANUSCRIPT_learned_representations_admet.md"
OUT = HERE / "PREPRINT_SUBMISSION.md"

# Figure number -> (file, regenerating script(s), caption). Ordered as they
# appear in the narrative.
FIGURES = [
    (0, "fig0_architecture_v2.png", "architecture_figure_v2.py",
     "System schematic. Molecular graphs feed the learned multi-task "
     "ensemble oracle; the random forest sits beside it as an explicit "
     "descriptor comparator; the calibrated decision engine (SPRT, "
     "conformal and selective prediction, abductive discovery) turns the "
     "oracle's uncertainty into a traceable go/no-go call, with every step "
     "logged to a DuckDB lineage store."),
    (1, "fig_transfer_curves.png", "train_multitask_gnn.py, dl_forward/figures.py",
     "Data-efficiency transfer curves. A shared multi-task graph encoder "
     "improves data-poor endpoints (hERG AUROC +0.008..+0.027, HIA "
     "+0.058..+0.071 at 25-50% data, Caco2 MAE -0.11..-0.17 at every "
     "fraction) over single-task graph baselines, without a raw-accuracy "
     "supremacy claim over the descriptor baseline."),
    (2, "fig_pretrain_ablation.png", "pretrain_ablation.py, dl_forward/figures.py",
     "Self-supervised attribute-mask pretraining ablation. Classification "
     "deltas stay within seed noise; single-task regression (Solubility) "
     "is the one effect that clears it, MAE -0.126 +/- 0.053 at f=0.10."),
    (3, "fig_ensemble_calibration.png", "make_ensemble_uncertainty.py, dl_forward/figures.py",
     "Deep-ensemble calibration. The K=5 ensemble is the best-calibrated "
     "graph model (lowest NLL 0.482, Brier 0.153, AURC 0.126 among graph "
     "methods); the descriptor baseline remains strongest on raw ECE, "
     "which is reported rather than contested."),
    (4, "fig_conformal_efficiency.png", "make_ensemble_uncertainty.py, dl_forward/figures.py",
     "Conformal set efficiency and selective prediction under scaffold "
     "shift. The ensemble gives the sharpest 90%-coverage sets of any "
     "graph model and undercuts the descriptor baseline on AMES, hERG, "
     "and HIA."),
    (5, "fig_attention_probe.png", "attention_attribution.py, dl_forward/figures.py",
     "Attention-attribution probe. Node-level attention does not recover "
     "the aromatic/basic-amine salience rule (AUROC ~0.5 on hERG and BBB), "
     "reported as a negative result and a limitation."),
    (6, "fig_campaign_efficiency.png", "e8_campaign_learned.py, dl_forward/figures.py",
     "End-to-end autonomous campaign with the learned oracle. SPRT returns "
     "GO on 3 of 4 classification endpoints and spends 150 versus a "
     "213 fixed-sample budget, a 29.7% aggregate reduction; the harder "
     "cases (BBB weak shift, HIA undecided) are reported in full."),
]

HEADER = (
    "<!-- GENERATED FILE. Do not edit by hand. Regenerate with "
    "`python pilot_phd/preprint/dl_forward/make_submission.py` after editing "
    "MANUSCRIPT_learned_representations_admet.md. -->\n\n"
)


def figure_block() -> str:
    lines = ["\n---\n\n## Figures\n"]
    for num, fname, script, caption in FIGURES:
        lines.append(f"![Figure {num}. {caption} (Regenerated by "
                     f"`{script}`.)](figures/{fname})\n")
        lines.append(f"**Figure {num}.** {caption} Regenerated by "
                     f"`{script}`.\n")
    return "\n".join(lines)


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    # Insert the embedded-figure gallery immediately before the References
    # heading so figures sit with the body, ahead of the back matter.
    marker = "\n## Generative AI Disclosure\n"
    if marker in text:
        body, tail = text.split(marker, 1)
        out = HEADER + body + figure_block() + marker + tail
    else:
        out = HEADER + text + figure_block()
    OUT.write_text(out, encoding="utf-8")
    print(f"wrote {OUT.relative_to(HERE.parent.parent.parent)} "
          f"({len(out.splitlines())} lines, {len(FIGURES)} figures embedded)")


if __name__ == "__main__":
    main()
